// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCohtFhPARNLIHiZoW3KB_o_fz8pOfC9Fg',
    appId: '1:190561828452:android:7d3367870de0e66ec4a971',
    messagingSenderId: '190561828452',
    projectId: 'hiflutter-d7d7c',
    databaseURL: 'https://hiflutter-d7d7c-default-rtdb.firebaseio.com',
    storageBucket: 'hiflutter-d7d7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVBrzmv2621SmRxl0MH_Xj6lcxD5nFqJw',
    appId: '1:190561828452:ios:9ea1ebd14bc3f9c7c4a971',
    messagingSenderId: '190561828452',
    projectId: 'hiflutter-d7d7c',
    databaseURL: 'https://hiflutter-d7d7c-default-rtdb.firebaseio.com',
    storageBucket: 'hiflutter-d7d7c.appspot.com',
    iosClientId: '190561828452-9n4gkp691n4hlhhhdcakhiuk2temle7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.demofirebase',
  );
}
